@echo off
setlocal ENABLEDELAYEDEXPANSION

REM =========================================
REM One-click install / run (stable)
REM Filename: run_app.bat (ASCII-only)
REM Generated by scripts\project_launcher.py
REM Project type: frontend_only
REM =========================================

pushd "%~dp0"
if not exist "logs" mkdir "logs" >nul 2>nul

echo =========================================
echo   One-click install / run (stable)
echo =========================================
echo.

echo [1/6] Checking Python...
where python >nul 2>&1
if errorlevel 1 (
  echo.
  echo [ERROR] Python not found. Please install Python 3.10+ first.
  echo Download: https://www.python.org/downloads/
  echo.
  pause
  popd
  exit /b 1
)

where node >nul 2>&1
if errorlevel 1 (
  echo [ERROR] Node.js not found. Install Node.js 20 or newer: https://nodejs.org/
  pause
  popd
  exit /b 1
)
where npm >nul 2>&1
if errorlevel 1 (
  echo [ERROR] npm not found. Reinstall Node.js from https://nodejs.org/
  pause
  popd
  exit /b 1
)
where cargo >nul 2>&1
if errorlevel 1 (
  echo [ERROR] Cargo not found. Install Rust stable: https://rustup.rs/
  pause
  popd
  exit /b 1
)

echo [2/6] Creating venv (.venv) if needed...
if not exist ".venv\Scripts\python.exe" (
  python -m venv ".venv" 1>>"logs\bootstrap.log" 2>>&1
  if errorlevel 1 (
    echo [WARN] Failed to create venv. Falling back to system Python.
  )
)

set "PYEXE=%~dp0.venv\Scripts\python.exe"
if not exist "%PYEXE%" set "PYEXE=python"

echo [3/6] Auto-fix + install dependencies...
"%PYEXE%" "scripts\project_launcher.py" --root "%CD%" --venv ".venv" --ensure-only 1>>"logs\ensure.log" 2>>&1
if errorlevel 1 (
  echo [WARN] Auto-fix or install step reported issues. See logs\ensure.log.
) else (
  echo [OK] Auto-fix and install step completed.
)



echo [4/6] Starting backend or local app...
echo Start time: %DATE% %TIME%
echo [4/6] Backend not detected. Skipping backend startup.

echo [5/6] Starting frontend (Node project)...
echo [INFO] Frontend dir: .
cd /d "."
if errorlevel 1 (
  echo [WARN] Frontend cd failed for path: .
) else (
  start "Frontend" /d "%~dp0." cmd /c "npm install 1>>""%~dp0logs\frontend.log"" 2>>&1 ^&^& npm run dev 1>>""%~dp0logs\frontend.log"" 2>>&1"
)
cd /d "%~dp0"
echo [6/6] Waiting for the local app...
"%PYEXE%" "scripts\wait_for_http.py" "http://127.0.0.1:4174/api/health" 30 "lingxi-summary-lab" 1>>"logs\launcher.log" 2>>&1
if errorlevel 1 (
  echo [ERROR] The local app did not become ready. See logs\frontend.log and logs\launcher.log.
) else (
  start "" "http://127.0.0.1:4174"
)


echo.
echo =========================================
echo Startup flow finished.
echo Logs directory: %CD%\logs
echo Close Backend / Frontend / GUI windows to stop services.
echo =========================================
echo.
pause
popd
endlocal
